"""initial schema

Revision ID: edb492ee76fb
Revises: 
Create Date: 2026-06-23 18:46:46.705756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'edb492ee76fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('permission', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='reels_automation'
    )
    op.create_index(op.f('ix_reels_automation_permissions_id'), 'permissions', ['id'], unique=False, schema='reels_automation')
    op.create_index(op.f('ix_reels_automation_permissions_name'), 'permissions', ['name'], unique=True, schema='reels_automation')
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='reels_automation'
    )
    op.create_index(op.f('ix_reels_automation_users_email'), 'users', ['email'], unique=True, schema='reels_automation')
    op.create_index(op.f('ix_reels_automation_users_id'), 'users', ['id'], unique=False, schema='reels_automation')
    op.create_table('profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['reels_automation.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='reels_automation'
    )
    op.create_index(op.f('ix_reels_automation_profiles_id'), 'profiles', ['id'], unique=False, schema='reels_automation')
    op.create_table('user_permissions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['reels_automation.permissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['reels_automation.users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'permission_id'),
    schema='reels_automation'
    )
    op.create_table('channels',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('niche', sa.String(length=100), nullable=False),
    sa.Column('target_audience', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('tone_of_voice', sa.String(length=100), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('daily_video_count', sa.Integer(), nullable=False),
    sa.Column('posting_hours', sa.ARRAY(sa.Time()), nullable=False),
    sa.Column('base_hashtags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['reels_automation.profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='reels_automation'
    )
    op.create_index(op.f('ix_reels_automation_channels_id'), 'channels', ['id'], unique=False, schema='reels_automation')
    op.create_index(op.f('ix_reels_automation_channels_profile_id'), 'channels', ['profile_id'], unique=False, schema='reels_automation')
    op.create_table('platform_configs',
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('platform_type', sa.String(length=50), nullable=False),
    sa.Column('credentials_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('platform_specific_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['reels_automation.channels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'platform_type', name='uq_channel_platform'),
    schema='reels_automation'
    )
    op.create_index(op.f('ix_reels_automation_platform_configs_channel_id'), 'platform_configs', ['channel_id'], unique=False, schema='reels_automation')
    op.create_index(op.f('ix_reels_automation_platform_configs_id'), 'platform_configs', ['id'], unique=False, schema='reels_automation')
    op.create_table('video_metadata',
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('hook_text', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('generated_hashtags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('video_path', sa.String(length=500), nullable=True),
    sa.Column('audio_path', sa.String(length=500), nullable=True),
    sa.Column('generation_status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['reels_automation.channels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='reels_automation'
    )
    op.create_index(op.f('ix_reels_automation_video_metadata_channel_id'), 'video_metadata', ['channel_id'], unique=False, schema='reels_automation')
    op.create_index(op.f('ix_reels_automation_video_metadata_id'), 'video_metadata', ['id'], unique=False, schema='reels_automation')
    op.create_table('video_publish_statuses',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('platform_type', sa.String(length=50), nullable=False),
    sa.Column('publish_status', sa.String(length=20), nullable=False),
    sa.Column('platform_video_id', sa.String(length=255), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['reels_automation.video_metadata.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', 'platform_type', name='uq_video_platform'),
    schema='reels_automation'
    )
    op.create_index(op.f('ix_reels_automation_video_publish_statuses_id'), 'video_publish_statuses', ['id'], unique=False, schema='reels_automation')
    op.create_index(op.f('ix_reels_automation_video_publish_statuses_video_id'), 'video_publish_statuses', ['video_id'], unique=False, schema='reels_automation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reels_automation_video_publish_statuses_video_id'), table_name='video_publish_statuses', schema='reels_automation')
    op.drop_index(op.f('ix_reels_automation_video_publish_statuses_id'), table_name='video_publish_statuses', schema='reels_automation')
    op.drop_table('video_publish_statuses', schema='reels_automation')
    op.drop_index(op.f('ix_reels_automation_video_metadata_id'), table_name='video_metadata', schema='reels_automation')
    op.drop_index(op.f('ix_reels_automation_video_metadata_channel_id'), table_name='video_metadata', schema='reels_automation')
    op.drop_table('video_metadata', schema='reels_automation')
    op.drop_index(op.f('ix_reels_automation_platform_configs_id'), table_name='platform_configs', schema='reels_automation')
    op.drop_index(op.f('ix_reels_automation_platform_configs_channel_id'), table_name='platform_configs', schema='reels_automation')
    op.drop_table('platform_configs', schema='reels_automation')
    op.drop_index(op.f('ix_reels_automation_channels_profile_id'), table_name='channels', schema='reels_automation')
    op.drop_index(op.f('ix_reels_automation_channels_id'), table_name='channels', schema='reels_automation')
    op.drop_table('channels', schema='reels_automation')
    op.drop_table('user_permissions', schema='reels_automation')
    op.drop_index(op.f('ix_reels_automation_profiles_id'), table_name='profiles', schema='reels_automation')
    op.drop_table('profiles', schema='reels_automation')
    op.drop_index(op.f('ix_reels_automation_users_id'), table_name='users', schema='reels_automation')
    op.drop_index(op.f('ix_reels_automation_users_email'), table_name='users', schema='reels_automation')
    op.drop_table('users', schema='reels_automation')
    op.drop_index(op.f('ix_reels_automation_permissions_name'), table_name='permissions', schema='reels_automation')
    op.drop_index(op.f('ix_reels_automation_permissions_id'), table_name='permissions', schema='reels_automation')
    op.drop_table('permissions', schema='reels_automation')
    # ### end Alembic commands ###
